name: update-refresh

on:
  push:
    branches: ["master"]

jobs:
  run_build_update_job:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and update current build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            exec bash \-l
            pnpm -v
